language: generic
sudo: required #need root user access for all builds.
service:
  - docker

before_install:
  - docker build -t autodidakt/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true autodidakt/docker-react npm run test -- --coverage

